name: ferreira-scrutiny

services:
  scrutiny:
    container_name: scrutiny_app
    image: ghcr.io/analogj/scrutiny:master-omnibus
    restart: unless-stopped
    privileged: true
    ports:
      - target: 8080
        published: "5080"
        protocol: tcp
      - target: 8086
        published: "5086"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /opt/scrutiny/config
      - type: bind
        source: /DATA/AppData/$AppID/influxdb
        target: /opt/scrutiny/influxdb
      - type: bind
        source: /run/udev
        target: /run/udev
        read_only: true
    devices:
      - /dev/sda:/dev/sda
      - /dev/sdb:/dev/sdb
    cap_add:
      - SYS_RAWIO

x-casaos:
  architectures:
    - amd64
    - arm64
  author: Igor
  developer:  AnalogJ
  category: Utilities
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/scrutiny-light.png
  index: /
  main: scrutiny
  is_uncontrolled: false
  port_map: "5080"
  scheme: http
  store_app_id: $AppID
  title:
    custom: "Scrutiny"
    en_us: Scrutiny