name: ferreira-jellyfin

services:
  jellyfin:
    container_name: jellyfin
    image: ghcr.io/jellyfin/jellyfin:10.10.6
    restart: unless-stopped
    privileged: false
    network_mode: host
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/cache
        target: /cache
      - type: bind
        source: /DATA/Media
        target: /media
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8096/health

x-casaos:
  architectures:
    - amd64
    - arm64
  category: Media
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin.png
  index: /
  main: jellyfin
  is_uncontrolled: false
  port_map: "8096"
  scheme: http
  store_app_id: ferreira-jellyfin
  title:
    en_us: Jellyfin
