name: ferreira-jellyfin

services:
  jellyfin:
    container_name: jellyfin_app
    image: ghcr.io/jellyfin/jellyfin:10.10.6
    restart: unless-stopped
    network_mode: host
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/AppData/$AppID/cache
        target: /cache
      - type: bind
        source: /DATA/Media
        target: /media

x-casaos:
  architectures:
    - amd64
    - arm64
  author: Igor
  developer: Jellyfin
  category: Media
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/jellyfin-light.png
  index: /
  main: jellyfin
  is_uncontrolled: false
  port_map: "8096"
  scheme: http
  store_app_id: $AppID
  title:
    custom: "Jellyfin"
    en_us: Jellyfin
