name: ferreira-nextcloud

services:
  nextcloud:
    container_name: nextcloud
    image: docker.io/library/nextcloud:31
    restart: unless-stopped
    privileged: false
    network_mode: bridge
    ports:
      - target: 80
        published: "8000"
        protocol: tcp                
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/var/www/html
        target: /var/www/html
      - type: bind
        source: /DATA/Documents
        target: /var/www/html/data

x-casaos:
  architectures:
    - amd64
    - arm64
  category: Cloud
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/nextcloud.png
  index: /
  is_uncontrolled: false
  main: nextcloud
  port_map: "8000"
  scheme: http
  store_app_id: ferreira-nextcloud
  title:
    en_us: Nextcloud
