name: ferreira-dozzle

services:
  dozzle:
    container_name: dozzle_app
    image: ghcr.io/amir20/dozzle:v8.12.6
    restart: unless-stopped
    ports:
      - target: 8080
        published: "7070"
        protocol: tcp
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock

x-casaos:
  architectures:
    - amd64
    - arm64
  author: Igor
  developer: amir20
  category: Utilities
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/dozzle-light.png
  index: /
  main: dozzle
  is_uncontrolled: false
  port_map: "7070"
  scheme: http
  store_app_id: $AppID
  title:
    custom: "Dozzle"
    en_us: Dozzle
