name: ferreira-manyfold

services:
  manyfold:
    container_name: manyfold
    image: ghcr.io/manyfold3d/manyfold-solo:0.105.0
    restart: unless-stopped
    privileged: false
    network_mode: bridge
    ports:
      - target: 3214
        published: "3214"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Gallery/Models
        target: /models
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - SECRET_KEY_BASE=a_nice_long_random_string
    security_opt:
      - no-new-privileges:true
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    cap_drop:
      - ALL
    hostname: manyfold

x-casaos:
  architectures:
    - amd64
    - arm64
  author: Igor
  category: 3D Printing
  developer: Manyfold
  hostname: "manyfold"
  icon: https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/manyfold-logo.png
  index: /
  is_uncontrolled: false
  main: manyfold
  port_map: "3214"
  scheme: http
  store_app_id: ferreira-manyfold
  title:
    custom: "Manyfold"
    en_us: Manyfold