name: ferreira-manyfold

services:
  manyfold:
    container_name: manyfold_app
    image: ghcr.io/manyfold3d/manyfold:0.107.0
    restart: unless-stopped
    ports:
      - target: 3214
        published: "3214"
        protocol: tcp
    depends_on:
      postgres:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    volumes:
      - type: bind
        source: /DATA/Documents/Models
        target: /models
    environment:
      - DATABASE_ADAPTER=postgresql
      - DATABASE_HOST=postgres
      - DATABASE_NAME=manyfold
      - DATABASE_USER=manyfold
      - DATABASE_PASSWORD=manyfold
      - SECRET_KEY_BASE=a_nice_long_random_string
      - REDIS_URL=redis://redis:6379/1
      - PGID=$PGID
      - PUID=$PUID
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - DAC_OVERRIDE
      - SETUID
      - SETGID
    networks:
      - manyfold
    stop_grace_period: 30s

  postgres:
    container_name: manyfold_database
    image: postgres:15
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/postgres
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=manyfold
      - POSTGRES_USER=manyfold
      - POSTGRES_PASSWORD=manyfold
    networks:
      - manyfold
    stop_grace_period: 30s

  redis:
    container_name: manyfold_cache
    image: redis:7
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/redis
        target: /data
    command:
      - redis-server
      - --save 60 1
      - --loglevel warning
    networks:
      - manyfold
    stop_grace_period: 30s

networks:
  manyfold:
    name: manyfold
    driver: bridge

x-casaos:
  architectures:
    - amd64
    - arm64
  author: Igor
  developer: Manyfold 3D
  category: 3D Printing
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/manyfold.png
  index: /
  is_uncontrolled: false
  main: manyfold
  port_map: "3214"
  scheme: http
  store_app_id: $AppID
  title:
    custom: "Manyfold"
    en_us: Manyfold