name: ferreira-qbittorrent

services:
  qbittorrent:
    container_name: qbittorrent
    image: lscr.io/linuxserver/qbittorrent:5.0.4-r0-ls387
    restart: unless-stopped
    ports:
      - target: 8080
        published: "8080"
        protocol: tcp
      - target: 6881
        published: "6881"
        protocol: tcp
      - target: 6881
        published: "6881"
        protocol: udp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /DATA/Downloads
        target: /downloads
      - type: bind
        source: /DATA/Media
        target: /Media
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=$TZ
      - TORRENTING_PORT=6881
      - WEBUI_PORT=8080

x-casaos:
  architectures:
    - amd64
    - arm64
  author: Igor
  developer: 
  category: Downloader
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/qbittorrent.png
  index: /
  main: qbittorrent
  is_uncontrolled: false
  port_map: "8080"
  scheme: http
  store_app_id: ferreira-qbittorrent
  title:
    en_us: qBittorrent
