name: ferreira-esphome

services:
  esphome:
    container_name: esphome_app
    image: ghcr.io/esphome/esphome:2025.3
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    environment:
      - PASSWORD=esphome
      - USERNAME=esphome

x-casaos:
  architectures:
    - amd64
    - arm64
  author: Igor
  developer: Open Home Foundation
  category: Home Automation
  hostname: ""
  icon: https://cdn.jsdelivr.net/gh/selfhst/icons/png/esphome-light.png
  index: /
  main: esphome
  is_uncontrolled: false
  port_map: "6052"
  scheme: http
  store_app_id: $AppID
  title:
    custom: "ESPHome"
    en_us: ESPHome
