name: ferreira-esphome

services:
  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome:2025.3
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/config
        target: /config
      - type: bind
        source: /etc/localtime
        target: /etc/localtime
        read_only: true
    environment:
      - PASSWORD=esphome
      - USERNAME=esphome

x-casaos:
  architectures:
    - amd64
    - arm64
  author: Igor
  developer: Igor
  category: Home Automation
  icon: https://icon.casaos.io/main/all/esphome.png
  index: /
  main: esphome
  is_uncontrolled: false
  port_map: "6052"
  scheme: http
  store_app_id: ferreira-esphome
  title:
    en_us: ESPHome
