name: ferreira-photoprism

services:
  photoprism:
    container_name: photoprism
    image: docker.io/photoprism/photoprism:250321
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    ports:
      - target: 2342
        published: "2342"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/storage
        target: /photoprism/storage
      - type: bind
        source: /DATA/Gallery
        target: /photoprism/originals
      - type: bind
        source: /DATA/Downloads
        target: /photoprism/import
    environment:
      - PHOTOPRISM_ADMIN_USER=admin
      - PHOTOPRISM_ADMIN_PASSWORD=insecure
      - PHOTOPRISM_UPLOAD_NSFW=true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    stop_grace_period: 10s
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:2342/api/v1/status

x-casaos:
  architectures:
    - amd64
    - arm64
  author: Igor
  category: Gallery
  developer: PhotoPrism
  icon: https://icon.casaos.io/main/all/photoprism.png
  index: /
  is_uncontrolled: false
  main: photoprism
  port_map: "2342"
  scheme: http
  store_app_id: ferreira-photoprism
  title:
    custom: "PhotoPrism"
    en_us: PhotoPrism