name: ferreira-photoprism

services:
  photoprism:
    container_name: photoprism
    image: docker.io/photoprism/photoprism:250321
    restart: unless-stopped
    privileged: true
    network_mode: bridge
    depends_on:
      - photoprism_db
    ports:
      - target: 2342
        published: "2342"
        protocol: tcp
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/storage
        target: /photoprism/storage
      - type: bind
        source: /DATA/Gallery
        target: /photoprism/originals
      - type: bind
        source: /DATA/Downloads
        target: /photoprism/import
    environment:
      PHOTOPRISM_ADMIN_USER: "admin"
      PHOTOPRISM_ADMIN_PASSWORD: "insecure"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "photoprism_db:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "photoprism"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    stop_grace_period: 10s
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:2342/api/v1/status"]

  photoprism_db:
    container_name: photoprism_db
    image: docker.io/mariadb:11
    restart: unless-stopped
    command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - type: bind
        source: /DATA/AppData/$AppID/database
        target: /var/lib/mysql
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "photoprism"
      MARIADB_ROOT_PASSWORD: "insecure"
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: true
      MARIADB_MYSQL_LOCALHOST_USER: 1
      MARIADB_MYSQL_LOCALHOST_GRANTS: USAGE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    stop_grace_period: 10s

x-casaos:
  architectures:
    - amd64
    - arm64
  author: Igor
  developer: PhotoPrism
  category: Gallery
  icon: https://icon.casaos.io/main/all/photoprism.png
  index: /
  main: photoprism
  is_uncontrolled: false
  port_map: "2342"
  scheme: http
  store_app_id: ferreira-photoprism
  title:
    en_us: PhotoPrism